name: Deploy with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_run:
    workflows: ["Sync with Upstream"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout Repository
    #   uses: actions/checkout@v4

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd ~/docker/gem-web
          git pull origin main
          docker compose down && docker compose pull && docker compose up -d

